# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Unit-GTestRunner
version:      0.02
version_from: lib/Test/Unit/GTestRunner.pm
installdirs:  site
requires:
    Gtk2:                          0
    Gtk2::GladeXML:                0
    Locale::TextDomain:            1.16
    Test::Unit:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
